### ISSUE TITLE
CSS/jquery van een image werkt niet lekker

### ISSUE THREAD

**Issue by Nickforall** [cle3-group8/scoreboard#1]
Alles wordt gepushed in een aparte `ul`, en binnen de huidige setup kan die officieel niet in de li, het display type moet aangepast worden, en een stukje JS moet veranderd worden.

Ik ga van het weekend kijken of ik dit kan fixen.

**Comment by Goef** [comment]
Is goed thanks! , ik verander de kleuren aan volgens een kleuren pallet!
